CREATE TABLE beatmaps (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL,
	md5 VARCHAR(127) NOT NULL UNIQUE,
	author VARCHAR(1024) NOT NULL,
	title VARCHAR(1024) NOT NULL,
	diff_name VARCHAR(1024) NOT NULL,
	creator VARCHAR(127) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE scores (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL,
	replay_md5 VARCHAR(127) NOT NULL,
	beatmap_id INT NOT NULL,
	player VARCHAR(127) NOT NULL,
	accuracy DOUBLE(14,8) NOT NULL,
	mods BIGINT UNSIGNED NOT NULL,
	max_combo INT UNSIGNED NOT NULL,
	misses INT UNSIGNED NOT NULL,
	calculated TINYINT(4) NOT NULL,
	total_pp DOUBLE(14,8) NOT NULL,
	PRIMARY KEY(id)
);
